name: build

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      test_windows:
        description: 'Test on Windows'
        type: boolean
        default: true
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup VSWhere.exe
      uses: warrenbuckley/Setup-VSWhere@v1

    - name: VSWhere MSBuild
      shell: pwsh
      run: |
        vswhere -version [15,17) -property installationPath
