name: build

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      test_windows:
        description: 'Test on Windows'
        type: boolean
        default: true

jobs:
  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup VSWhere.exe
      uses: microsoft/vswhere@v3.1.4

    - name: VSWhere MSBuild
      run: vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
